# Generated by Django 5.0.14 on 2025-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cell', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('operator', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_status', models.CharField(max_length=100)),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
            ],
        ),
    ]
