# Generated by Django 5.0.14 on 2025-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interlinkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonedata',
            name='hide',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
