# Generated by Django 5.0.14 on 2025-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tableonedata_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonedata',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
