# Generated by Django 5.0.14 on 2025-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tableonedata_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe_calibrations',
            name='coefficent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probe_calibrations',
            name='high_count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probe_calibrations',
            name='high_ref',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probe_calibrations',
            name='low_count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probe_calibrations',
            name='low_ref',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
