# Generated by Django 5.0.14 on 2025-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_settings',
            name='a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='o1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='parameter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='probe_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='selected_mastering',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='selected_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_settings',
            name='shift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
