# Generated by Django 5.0.14 on 2025-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_master_settings_a_alter_master_settings_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField()),
                ('stop_time', models.PositiveIntegerField()),
            ],
        ),
    ]
