# Generated by Django 5.0.14 on 2025-08-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_timesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesetting',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timesetting',
            name='stop_time',
            field=models.CharField(max_length=100),
        ),
    ]
