# Generated by Django 5.0.14 on 2025-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_timesetting_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cell', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('operator', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_status', models.CharField(max_length=100)),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StationOne',
                'managed': False,
            },
        ),
    ]
