# Generated by Django 5.0.14 on 2025-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_stationone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_value', models.CharField(max_length=255)),
                ('part_model', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
